apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: javadiag
  namespace: <namespace>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: javadiag
subjects:
- kind: ServiceAccount
  name: javadiag
  namespace: amqbroker
